### PR TITLE
Bump version of last title sequence to 0.4.14

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by Broxzier** [comment]
With this change, the hash of the release zip also changes to this, which needs to be updated on the OpenRCT2 repo: 54f234cf9ae1e6c0b58e91bf0814371779a68f4f

**Comment by Broxzier** [comment]
I've now also removed the release folder, which wasn't used for releases anyway. Release artifacts can be found on the release page on GitHub instead.

**Comment by Basssiiie** [comment]
Are you still planning on doing anything with the feedback in #13?

**Comment by AaronVanGeffen** [comment]
I like the changes to the first few shots. @Basssiiie, are you happy as well?

**Comment by Basssiiie** [comment]
I like the improvement of the first few shots as well, it makes it more interesting. 🙂

Furthermore, I've had contact with Broxzier on Discord discussing some of the other feedback, currently mainly whether to add some extra scenes to some of the first few parks to balance the screen-time a bit more for fairness. One example I noticed/mentioned was that the 2nd park only has 25 seconds of screen-time, while the one before the last one has more than 50 seconds of screen-time.

The rest of the feedback from the PR hasn't really come to discussion yet.

**Comment by Basssiiie** [comment]
I assume the idea is to have it in the next release right? It would be nice to have everything ironed out a bit in advance this time and not at the last second, but that of course depends on @Broxzier's available time and schedule.

**Comment by AaronVanGeffen** [comment]
While it might not be perfect in its current form, I think it would be good not to get too bogged down in trying to get it to be perfect. Adjusting the current sequence to match up with the music etc. is no trivial matter, either, though. Sufficed to say some lessons were learned on not making this one person's sole responsibility.

Personally, I think we should merge the sequence as-is, preferably sooner rather than later, such that it can make it into the next release.

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by Basssiiie** [comment]
IMHO it shouldn't be that difficult to shift scenes around as the sequence can be opened in notepad making cut/pasting certain parts around easier while keeping the same timing. The only tricky thing is that the moving monorail part is a bit harder to move and keep it in sync with the timing of the music.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
I think it’s time to release the new title sequence while it’s still somewhat fresh. I’m sure that stuff could be improved, but this is prime bikeshedding material.

@Basssiiie If you’d like to volunteer for creating the next title sequence/running the next context, we would of course be very happy to let you do that.

**Comment by Basssiiie** [comment]
@Gymnasiast I would love to help out in case I have the time next time around. I would prefer to collaborate on it though, to avoid running into the same issues with working on it fully solo, as we had with this title sequence.

**Comment by Broxzier** [comment]
I have plenty of ideas for future title sequences, though I personally would like to drop the contest part and have people contribute to one big part together, or otherwise have all entries themed after an original contest, where every person gets one of the pre-determined shots (like Aaron suggested, something like the "Park X but Beautiful" series by Deurklink).

**Comment by Basssiiie** [comment]
Sounds good! Might be a nice idea to organize some kind of brainstorm session when the time for a new sequence comes around. 🙂

**Pull request merged**
