### PR TITLE
Add v0.4.13 title sequence

### PR DESCRIPTION
**Pull request by Broxzier**
Here's the new title sequence! This time, I decided to use all the parks that were entered in the title sequence contest that was hosted together with Deurklink, showing them in order of their placement in the contest.

### CODE REVIEW

**Comment by Broxzier** [comment]
To check this title sequence out before it's in-game, place this file in your sequence folder and remove the .zip extension (keep the .parkseq extension though!): [openrct2.parkseq.zip](https://github.com/user-attachments/files/16484913/openrct2.parkseq.zip), then select it as the sequence that the game plays in the options menu.

**Review by AaronVanGeffen — APPROVED** [review]
Nice work! Admittedly, I had my reservations when I read you'd included every submission, but you've turned it into a really nice sequence to watch.

It is a little on the long side, though, with the theme music playing 2.5 times, at least, but it is fun to watch the whole thing. My favourite part is probably following the monorail train around over a dense area, haha.

Thanks again for compiling this sequence!

**Comment by MaxMallon** [comment]
I think it's a little strange how the 2nd lowest voted park has double the screentime of the 2nd highest voted park. In fact, our park is visible the very shortest, even last place is visible for longer :/
While it's admirable to try and include everything, it results in a lot of 6ish seconds long shots, vs the 11ish seconds from the previous sequences, making it feel rushed, I think. 

There's some cool bits in the sequence though

**Review by Gymnasiast — APPROVED** [review]
I would have preferred it if this wasn’t submitted on the eleventh hour. It leaves no room for review.

Nevertheless, I don’t want to be _that guy_.

**Comment by Basssiiie** [comment]
I would have liked to review it too. 🫠

**Comment by Gymnasiast** [comment]
Practically speaking, this was a matter of merging now or waiting a month (until the next release).

**Comment by Basssiiie** [comment]
Which would have been fine tho right? It's not like we were in dire need of replacing the old one. 😅

**Comment by Gymnasiast** [comment]
@Basssiiie We have decided to postpone this after all. Feel free to review.

**Comment by Basssiiie** [comment]
Thanks! 🙂 I like the title sequence, there are some really nice scenes and shots in there. My favourite's are Lurker's park, Ballpit+Deurklink+Monsterbux's park (1st scene is so-so tho), and MartinTrainFreak's park. The monorail ride in Martin's park is very nice even though I generally like moving camera's in the title sequence. 

My nitpicks:

- The first 2 scenes are very similar and look like it's just a rotate. I'd place either the first scene a bit further away from the entrance, or place the second scene a bit further into the park. The entrance can still be a reference point but doesn't need to be in full frame for both intro scenes. These first scenes are gonna be the most watched scenes and it's a bit boring it's the exact same thing just from another angle.
- The last scenes in WidgetKitty's park and Mattm's park have mostly just trees on half the screen when playing it on 1080p. Maybe move it a bit more into the park, away from the forest?
- I can understand wanting to have everyone included, but Isao's park does feel a bit unfinished (I believe it was). Especially in the second half of the scenes of this park.
- I do get lag spikes sometimes in the middle of a scene, thought that's likely something for a seperate issue?

**Comment by MaxMallon** [comment]
Aside from the park I worked on, I would prefer more 11ish seconds shots, and fewer 6ish seconds shots. 
They feel too brief and make the sequence feel kinda chaotic.

**Comment by AaronVanGeffen** [comment]
> I do get lag spikes sometimes in the middle of a scene, thought that's likely something for a seperate issue?

This may be due to another park loading. Unfortunately, this doesn't happen asynchronously yet.

**Comment by Broxzier** [comment]
Hey, thanks for your feedback @Basssiiie!

> The first 2 scenes are very similar and look like it's just a rotate. I'd place either the first scene a bit further away from the entrance, or place the second scene a bit further into the park. The entrance can still be a reference point but doesn't need to be in full frame for both intro scenes. These first scenes are gonna be the most watched scenes and it's a bit boring it's the exact same thing just from another angle.

The RCT2 and past few OpenRCT2 title sequences have all started this way, and I'd like to keep this somewhat tradition with our releases. Unlike the original, this one is actually synced with the music. I do get that it may feel a tad empty, though that does also serve its purpose for those who simply want to open their own parks. Players who actually want to watch the sequence can sit through, and then get to the more busy parts.

> The last scenes in WidgetKitty's park and Mattm's park have mostly just trees on half the screen when playing it on 1080p. Maybe move it a bit more into the park, away from the forest?

This was intentional. I've checked it on 1080p as well, and felt like this wouldn't be too out of place, while it also still works well for small/zoomed in windows.

> I can understand wanting to have everyone included, but Isao's park does feel a bit unfinished (I believe it was). Especially in the second half of the scenes of this park.

It's still worth showing in my opinion. The quality of these parks were all higher than some of the prebuild parks that have been used before.

**Comment by Basssiiie** [comment]
@Broxzier Thanks for your reply. 🙂

> I do get that it may feel a tad empty, though that does also serve its purpose for those who simply want to open their own parks

I'm not understanding this one. Why does it need to be empty for people who wanna open their own parks?

> This was intentional. I've checked it on 1080p as well, and felt like this wouldn't be too out of place, while it also still works well for small/zoomed in windows.

The place can still be shown while nudging it a little bit away from the forest. Would work on both 720p and 1080p.

> The quality of these parks were all higher than some of the prebuild parks that have been used before.

Not sure which ones were worse but also a bit strange to use as a baseline. Wouldn't one always want to make it as good as possible instead of just barely above the worst? 😅

I also agree that the timing for the different parks is a bit inconsistent.

**Comment by Basssiiie** [comment]
@AaronVanGeffen do they already pre-load in the middle of a scene? I would think they load at the end of the scene when the "load park" step in the title sequence is triggered. 😅

**Comment by Gymnasiast** [comment]
That is not yet implemented, but everything is in place to implement it.

**Pull request merged**
